### ISSUE TITLE
Ошибка на GetMessageResponse

### ISSUE THREAD

**Issue by maxkarelov** [QortexDevs/fnsapi#1]
Могли бы помочь с запросами на получение чеков?

После получения `<MessageId>fa2d9799-8049-460a-8391-bf6cfe328100</MessageId>`, делаю запрос `GetMessageResponse` и получаю 200 с `ProcessingStatus=COMPLETED`, но в `GetTicketResponse` ошибка 503 "Сервис недоступен"

Может быть сталкивались с подобной ошибкой? Master token был выдан 12.01.2021 ФНС

![image](https://user-images.githubusercontent.com/2924696/104567653-7554a080-5668-11eb-9acb-ebceb9c3046a.png)

Если повторяю этот запрос, то дальше получаю 500 с сообщением превышено время ответа сервиса

**Comment by NickMitin** [comment]
Мы сталкивались с проблемой, что 503 ошибка выдаётся в случае, если данные чека переданы в неверном формате. Чаще всего это происходит из-за формата даты и времени чека. 

Если вы можете показать исходный запрос с данными чека, то возможно я смогу помочь понять в чём дело.
